name: release

on:
  release:
    types: published
  workflow_dispatch:
jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.1

      - name: Upload to Nuget
        env:
          NUGET_DEPLOY_KEY: ${{ secrets.NUGET_DEPLOY_KEY }}
        run: |
          cd websocket-sharp/websocket-sharp-netstandard
          dotnet pack altwebsocket-sharp.csproj -c release
          dotnet nuget push bin/release/altwebsocket-sharp.1.0.6.nupkg --api-key $NUGET_DEPLOY_KEY --source https://api.nuget.org/v3/index.json
